# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2102cf8e775534e7f0c22e57b9ece5028dd3092335a0905ea5df152078b060f8d5e8d9ec4abd220440c303b97d1a8ff702a03d92ebcd15b97649dd70f8048e13

test:
  secret_key_base: 66e4019a5f65d12af11ce7eaf776432fa1c9cc918103de136e5547f9397e4b052a523955363fb4f3513d5b9aa22ae5e2f7391a3c696d49eeaad705bc67cfa2ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
